openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the embedded RAG chatbot to answer questions based on selected textbook content.

servers:
  - url: /api/rag
    description: RAG Chatbot Service Endpoint

paths:
  /query:
    post:
      summary: Query RAG Chatbot with selected text context
      operationId: queryRAGChatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - selected_text
                - chapter_id
              properties:
                query:
                  type: string
                  description: The user's question for the chatbot.
                  example: "What is Physical AI?"
                selected_text:
                  type: string
                  description: The text selected by the user from the textbook, used as context.
                  example: "Physical AI combines robotics with artificial intelligence to enable machines to interact with the physical world."
                chapter_id:
                  type: string
                  description: The ID of the chapter from which the text was selected.
                  example: "01-introduction"
      responses:
        '200':
          description: Successful response with the answer and source citations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer generated by the RAG chatbot.
                    example: "Physical AI is a field that integrates robotics and AI, allowing machines to interact with their environment."
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        chapter_id:
                          type: string
                          example: "01-introduction"
                        chapter_title:
                          type: string
                          example: "Introduction to Physical AI"
                        link:
                          type: string
                          format: url
                          example: "/docs/01-introduction#physical-ai-definition"
                        text_excerpt:
                          type: string
                          example: "Physical AI combines robotics with artificial intelligence to enable machines to interact with the physical world."
        '400':
          description: Invalid request, e.g., missing query or selected text.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Query and selected_text are required."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An internal server error occurred."
