# API Contracts: Agent Validator for RAG Chatbot

## Overview
This document defines the API contracts for the Agent Validator feature that validates user questions for relevance to Physical AI & Humanoid Robotics textbook content.

## OpenAPI Specification

```yaml
openapi: 3.0.3
info:
  title: Agent Validator API
  description: API for validating user questions for relevance to Physical AI & Humanoid Robotics textbook
  version: 1.0.0
paths:
  /query:
    post:
      summary: Validate and process user question
      description: Validates if the user question is relevant to Physical AI & Humanoid Robotics textbook before RAG processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: The user's question
                  example: "How does ROS 2 handle message passing between nodes?"
                user_id:
                  type: string
                  description: Optional user identifier
                  example: "user-123"
      responses:
        "200":
          description: Successful response with answer or rejection message
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - type: object
                    required: [answer, source_chunks]
                    properties:
                      answer:
                        type: string
                        description: The answer to the user's question
                        example: "ROS 2 uses a publish-subscribe model for message passing..."
                      source_chunks:
                        type: array
                        items:
                          type: object
                          properties:
                            content:
                              type: string
                            source:
                              type: string
                            page:
                              type: number
                        description: Source citations for the answer
                      validation:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [RELEVANT]
                          confidence:
                            type: number
                            minimum: 0
                            maximum: 1
                          processing_time_ms:
                            type: integer
                  - type: object
                    required: [message]
                    properties:
                      message:
                        type: string
                        description: Rejection message for irrelevant questions
                        example: "I can only answer questions related to the Physical AI & Humanoid Robotics textbook. Please ask questions about topics covered in the book such as ROS 2, Gazebo, Isaac Sim, sensors, or humanoid robotics."
                      validation:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [IRRELEVANT]
                          confidence:
                            type: number
                            minimum: 0
                            maximum: 1
                          processing_time_ms:
                            type: integer
        "400":
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                required: [error]
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Question is required"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                required: [error]
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Internal server error occurred"
      x-codegen-request-body-name: body

  /validate:
    post:
      summary: Validate question relevance only
      description: Validates if the user question is relevant to Physical AI & Humanoid Robotics textbook content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: The user's question to validate
                  example: "What's the best recipe for chocolate cake?"
      responses:
        "200":
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                required: [status, confidence, processing_time_ms]
                properties:
                  status:
                    type: string
                    enum: [RELEVANT, IRRELEVANT]
                    description: Whether the question is relevant to the textbook
                  confidence:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: Confidence level of the validation decision
                  processing_time_ms:
                    type: integer
                    description: Time taken for validation in milliseconds
                  reason:
                    type: string
                    description: Brief explanation for the validation decision
        "400":
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                required: [error]
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Question is required"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                required: [error]
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Validation service unavailable"
```

## Validation Service API

The agent validator service will expose these internal endpoints:

### POST /internal/validate-question
- Validates a question for relevance to Physical AI & Humanoid Robotics topics
- Input: JSON with `question` field
- Output: JSON with `status`, `confidence`, and `processing_time_ms`
- Timeout: 2 seconds maximum

## Error Handling

- All API endpoints follow standard HTTP status codes
- Client errors (4xx) return descriptive error messages
- Server errors (5xx) are logged for debugging
- Validation timeouts return appropriate fallback responses