# OpenAPI 3.0 Specification for RAG Chatbot API

openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the RAG Chatbot system, providing Q&A capabilities for the Physical AI Docusaurus book content.

servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /query:
    post:
      summary: Standard RAG Q&A
      operationId: queryStandard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's question about the book content.
      responses:
        '200':
          description: Successful response with the answer and source citations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The generated answer from the LLM.
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          description: Source markdown file path.
                        text_snippet:
                          type: string
                          description: Relevant text snippet from the source.
        '429':
          description: Rate limit exceeded for the LLM API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Rate limit exceeded. Please try again later."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Internal server error."

  /query-selection:
    post:
      summary: Answer based on user's selected text
      operationId: querySelection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - selected_text
                - question
              properties:
                selected_text:
                  type: string
                  description: The text selected by the user in the Docusaurus book.
                question:
                  type: string
                  description: An optional question to ask about the selected text.
      responses:
        '200':
          description: Successful response with the answer based on selected text.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The generated answer from the LLM, contextualized by selected text.
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          description: Source markdown file path (usually the one containing selected_text).
                        text_snippet:
                          type: string
                          description: Relevant text snippet from the selected text or related content.
        '429':
          description: Rate limit exceeded for the LLM API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Rate limit exceeded. Please try again later."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Internal server error."
